name: Deploy Frontend Only

on:
  push:
    branches: [ main ]
    paths: 
      - 'frontend/**'
      - '!frontend/Dockerfile'
      - '!frontend/.dockerignore'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        sparse-checkout: |
          frontend/
        sparse-checkout-cone-mode: false
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build React app
      run: npm run build
      env:
        REACT_APP_API_URL: https://joke-manager.vercel.app/api
        CI: false
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: frontend/build
        cname: false
